import {GnosisRule} from './GnosisRule';

export const gnosisRules: GnosisRule[] = [
  {
    gnosis: 1,
    ritualInterval: 3,
    ritualIntervalTimeUnit: 'hour',
    manaLimit: 10,
    manaPerTurn: 1,
    traitMax: 5,
    yantrasMax: 2,
    paradoxCreated: 1,
    combinedSpells: 1,
    obsessions: 1,
    highestArcanumMax: 3,
    otherArcanumMax: 2,
  },
  {
    gnosis: 2,
    ritualInterval: 3,
    ritualIntervalTimeUnit: 'hour',
    manaLimit: 11,
    manaPerTurn: 2,
    traitMax: 5,
    yantrasMax: 2,
    paradoxCreated: 1,
    combinedSpells: 1,
    obsessions: 1,
    highestArcanumMax: 3,
    otherArcanumMax: 3,
  },
  {
    gnosis: 3,
    ritualInterval: 1,
    ritualIntervalTimeUnit: 'hour',
    manaLimit: 12,
    manaPerTurn: 3,
    traitMax: 5,
    yantrasMax: 3,
    paradoxCreated: 2,
    combinedSpells: 2,
    obsessions: 2,
    highestArcanumMax: 4,
    otherArcanumMax: 3,
  },
  {
    gnosis: 4,
    ritualInterval: 1,
    ritualIntervalTimeUnit: 'hour',
    manaLimit: 13,
    manaPerTurn: 4,
    traitMax: 5,
    yantrasMax: 3,
    paradoxCreated: 2,
    combinedSpells: 2,
    obsessions: 2,
    highestArcanumMax: 4,
    otherArcanumMax: 4,
  },
  {
    gnosis: 5,
    ritualInterval: 30,
    ritualIntervalTimeUnit: 'minutes',
    manaLimit: 15,
    manaPerTurn: 5,
    traitMax: 5,
    yantrasMax: 4,
    paradoxCreated: 3,
    combinedSpells: 2,
    obsessions: 2,
    highestArcanumMax: 5,
    otherArcanumMax: 4,
  },
  {
    gnosis: 6,
    ritualInterval: 30,
    ritualIntervalTimeUnit: 'minutes',
    manaLimit: 20,
    manaPerTurn: 6,
    traitMax: 6,
    yantrasMax: 4,
    paradoxCreated: 3,
    combinedSpells: 3,
    obsessions: 3,
    highestArcanumMax: 5,
    otherArcanumMax: 5,
  },
  {
    gnosis: 7,
    ritualInterval: 10,
    ritualIntervalTimeUnit: 'minutes',
    manaLimit: 25,
    manaPerTurn: 7,
    traitMax: 7,
    yantrasMax: 5,
    paradoxCreated: 4,
    combinedSpells: 3,
    obsessions: 3,
    highestArcanumMax: 5,
    otherArcanumMax: 5,
  },
  {
    gnosis: 8,
    ritualInterval: 10,
    ritualIntervalTimeUnit: 'minutes',
    manaLimit: 30,
    manaPerTurn: 8,
    traitMax: 8,
    yantrasMax: 5,
    paradoxCreated: 4,
    combinedSpells: 3,
    obsessions: 3,
    highestArcanumMax: 5,
    otherArcanumMax: 5,
  },
  {
    gnosis: 9,
    ritualInterval: 1,
    ritualIntervalTimeUnit: 'minutes',
    manaLimit: 50,
    manaPerTurn: 9,
    traitMax: 9,
    yantrasMax: 6,
    paradoxCreated: 5,
    combinedSpells: 4,
    obsessions: 4,
    highestArcanumMax: 5,
    otherArcanumMax: 5,
  },
  {
    gnosis: 10,
    ritualInterval: 1,
    ritualIntervalTimeUnit: 'minutes',
    manaLimit: 75,
    manaPerTurn: 10,
    traitMax: 10,
    yantrasMax: 6,
    paradoxCreated: 5,
    combinedSpells: 4,
    obsessions: 4,
    highestArcanumMax: 5,
    otherArcanumMax: 5,
  },
];
