export enum SpellValueIds {
  title = 'title',
  highestArcanum = 'highestArcanum',
  highestArcanumValue = 'highestArcanumValue',
  isMagesHighestArcanum = 'isMagesHighestArcanum',
  additionalDice = 'additionalDice',
  symphaticRange = 'symphaticRange',
  temporalSympathy = 'temporalSympathy',
  extraReach = 'extraReach',
  activeSpells = 'activeSpells',
  notFromRulingArcana = 'notFromRulingArcana',
  inuredToSpell = 'inuredToSpell',
  numberOfPreviousParadoxRolls = 'numberOfPreviousParadoxRolls',
  dedicatedToolUsed = 'dedicatedToolUsed',
  additionalManaSpendForReducingParadox = 'additionalManaSpendForReducingParadox',
  additionalParadoxDices = 'additionalParadoxDices',
  sleeperWitnesses = 'sleeperWitnesses',
  paradoxDiceFromReach = 'paradoxDiceFromReach',
}
